name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      actions: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit-2.1.0-beta3"

    - name: Install luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install teal
      run: luarocks install tl
    - name: Install inspect
      run: luarocks install inspect

    - name: Build crates.nvim
      run: make build
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: lua
        commit_message: "chore: generate lua files"
    
    - name: Generate docs
      run: make doc
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: README.md doc/crates.txt
        commit_message: "chore: generate docs"
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: crates.nvim

    - name: Install neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
    
    - name: Install plenary.nvim
      uses: actions/checkout@v3
      with:
        repository: nvim-lua/plenary.nvim
        path: plenary.nvim

    - name: Run tests
      run: make test
      working-directory: crates.nvim
      timeout-minutes: 1

